### ISSUE TITLE
:zap: test improvement

### ISSUE THREAD

**Issue by lvenier** [SaaShup/netbox-docker-agent#101]
As per the introduction ofr hurl there is some missing changes to be done : 

- [x] README file is incorrect as still mentionning jest
- [x] package.json dependencies is obsolete

we need to have a proper way documenting how to run hurl locally to execute tests

**Comment by dzove855** [comment]
https://github.com/SaaShup/netbox-docker-agent/pull/104

**Comment by dzove855** [comment]
Merged
