### ISSUE TITLE
Error with new Version

### ISSUE THREAD

**Issue by mcordes92** [SaaShup/netbox-docker-agent#147]
After the Update to the new Version with this docker run command

docker run -d -p 10.212.0.211:1880:1880 -e DISABLE_SSL_CHECK=true -v /var/run/docker.sock:/var/run/docker.sock:rw -v netbox-docker-agent:/data --name netbox-docker-agent saashup/netbox-docker-agent

then i add the host in netbox

and after a minimal time this error appears in the netbox docker agent logs

netbox-docker-agent level=info version=0.40.0 msg="RequestError: self-signed certificate : https://10.212.255.253/api/plugins/docker/images/"

**Comment by lvenier** [comment]
Your log shows version 0.40. latest is 0.42.
Are you sure you pulled the latest version?

**Comment by mcordes92** [comment]
oh sorry my mistake. there was an error when pulling the image. now it works without any problems and I have all the data :)

**Comment by lvenier** [comment]
@mcordes92 great! Good news. Pls help and support us by starring the netbox docker plugin.
