### ISSUE TITLE
:sparkles: add hostname

### ISSUE THREAD

**Issue by lvenier** [SaaShup/netbox-docker-agent#157]
| Agent version |  Docker API Version |
| --- | --- |
| 1.X | 1.43 |

In the docker api it is possible to add hostname to populate the host file : 
```
ExtraHosts	
Array of strings
A list of hostnames/IP mappings to add to the container's /etc/hosts file. Specified in the form ["hostname:IP"].
```

It would be good to allow that configuration when we edit a container.
I suggest to have an extra field **extra_host** in the json with the following format : 
extra_host: ["hostname1:IP1","hostname2:IP2",....] defaulted as []

**Comment by olivn** [comment]
docker inspect  faf2a36c8b2c

    "HostConfig": {
             ....
            "DnsSearch": [],
            "ExtraHosts": [
                "host.local:10.11.12.13"
            ],



 
  
    docker exec -it  faf2a36c8b2c cat /etc/hosts
    
    127.0.0.1       localhost
    ::1     localhost ip6-localhost ip6-loopback
    fe00::0 ip6-localnet
    ff00::0 ip6-mcastprefix
    ff02::1 ip6-allnodes
    ff02::2 ip6-allrouters
    10.11.12.13     host.local
    192.168.2.5     faf2a36c8b2c

**Comment by lvenier** [comment]
https://github.com/SaaShup/netbox-docker-agent/pull/165
