### ISSUE TITLE
:sparkles: Add a log when Docker socket is not writable

### ISSUE THREAD

**Issue by fanshan** [SaaShup/netbox-docker-agent#23]
On the Agent boot phase we can add a log that will tell if the Docker socket (`/var/run/docker.sock`) is writable or not.

The level log if the socket is not writable is ERROR
The level log if the socket is writable is INFO

**Comment by fanshan** [comment]
First is to stderr the log. Adding /metrics flag is a good option too.

**Comment by lvenier** [comment]
@dzove855 you take care of it ?

**Comment by lvenier** [comment]
released in 0.21.1
