### ISSUE TITLE
:sparkles: Pull updated images

### ISSUE THREAD

**Issue by linkdd** [SaaShup/netbox-docker-agent#53]
| Netbox Version | Plugin Version | Agent Version |
| --- | --- | --- |
| 3.6.9 | 1.3.0 | 0.12.1 |

## Actual Behavior

Docker images are only pulled when created in Netbox.

## Desired Behavior

Updating an image in Netbox (its name or version or any other field) should trigger a pull as well.

**Comment by lvenier** [comment]
Updating an image should not exists :)

the right behavior is to only create image... the use of the latest tag is documented as follow in kubes : 
```
You should avoid using the :latest tag when deploying containers in production, because this makes it hard to track which version of the image is running and hard to roll back
```

Best approch is to connect your CICD to netbox : on release you trigger a create image in netbox to make accessible the new image...

**Comment by linkdd** [comment]
Here is a few use cases:

1. I have multiple containers using the same image. Updating the image's tag (the "version" field in Netbox) and then restarting the container is quicker than creating a new image, editing each container to use the new image, restarting them, removing the old one (to free some space on the host).

2. I made a typo in the image's name. Should I create a new one?

Netbox allows the updating of resources. If an "update" does not make sense, simply consider it as a "remove" followed by a "create". The user experience on Netbox will be improved 🙂
