### ISSUE TITLE
:children_crossing: Updating a container, or one of its sub-resource should recreate it automatically

### ISSUE THREAD

**Issue by linkdd** [SaaShup/netbox-docker-agent#54]
| Netbox Version | Plugin Version | Agent Version |
| --- | --- | --- |
| 3.6.9 | 1.3.0 | 0.12.1 |

## Actual Behavior

Whenever a modification is made on a container, we need to click on the "Recreate" button.

## Desired Behavior

This should be done automatically whenever a change is made on a container (or one of the subresource like `Port`, or `Mount`) in Netbox.

**Comment by lvenier** [comment]
Can it be implemented with a netbox webhook ?

**Comment by linkdd** [comment]
Not one, but many. A webhook is setup on a specific resource I believe, we would then need a webhook for `Container`, one for `Mount`, one for `Port`, etc...

**Comment by linkdd** [comment]
https://github.com/SaaShup/netbox-docker-plugin/pull/120 makes the "recreate" operation impossible in some states. Thus doing it automatically does not make sense anymore.

Anyway, I probably don't want to recreate the container if I update a label, or add a Netbox tag to it.
