### ISSUE TITLE
:children_crossing: Starting a container while it is being recreated fails

### ISSUE THREAD

**Issue by linkdd** [SaaShup/netbox-docker-agent#55]
| Netbox Version | Plugin Version | Agent Version |
| --- | --- | --- |
| 3.6.9 | 1.3.0 | 0.12.1 |

## Actual Behavior

While a container is being created, clicking on the "Start" will results in an error:

```json
{"message": "No such container: <container name>"}
```

## Desired Behavior

Actions performed on a container should be queued. This means that clicking on the "Start" button should wait for the container to be created before actually starting the container.

**Comment by lvenier** [comment]
I believe this feature should be done on the plugin.

We should not be able to use an image for a container as long as imageID is not set.

**Comment by linkdd** [comment]
Another use case: I am an impatient child who is clicking frenetically the "Recreate" button 🤣

If you consider #54, it is possible that many quick updates (done via CI or via an Ansible playbook that do not care about checking the journal entries to wait for things) would queue many actions at once. With a queue, everything will be done smoothly, without a queue all hell breaks loose.
