### ISSUE TITLE
:sparkles: The agent should synchronize the host's state in Netbox

### ISSUE THREAD

**Issue by linkdd** [SaaShup/netbox-docker-agent#56]
| Netbox Version | Plugin Version | Agent Version |
| --- | --- | --- |
| 3.6.9 | 1.3.0 | 0.12.1 |

## Actual Behavior

The agent is currently unidirectional: actions done in Netbox are applied on the host (adding an image, creating a container, ...).

This means that:

 - if a container creates anonymous volumes (via the `VOLUME /path` in the Dockerfile), there is currently no way to detect it in Netbox
 - if someone manually runs `docker pull` or `docker run` on the host, there is no way to see it in Netbox

## Desired Behavior

The agent should create the resources in Netbox to reflect the Docker host's state.

**Comment by lvenier** [comment]
Agree with "if a container creates anonymous volumes (via the VOLUME /path in the Dockerfile), there is currently no way to detect it in Netbox"

On the container creation we can inject the anonymous volume in netbox and the mount if possible. To be investigated.

The purpose of netbox is to be the source of truth. Then if you pull or un on the host you are beaking this rule. you should pull and run from netbox plugin.

**Comment by linkdd** [comment]
> _"if someone manually runs docker pull or docker run on the host, there is no way to see it in Netbox"_ The purpose of netbox is to be the source of truth. Then if you pull or un on the host you are beaking this rule. you should pull and run from netbox plugin.

Then the agent should revert the actions done manually on the host. Maybe we can take some inspiration from ArgoCD/Git/k8s here?

**Comment by lvenier** [comment]
this issue is kept for use case "if a container creates anonymous volumes (via the VOLUME /path in the Dockerfile), there is currently no way to detect it in Netbox"

Other issue to be created for comparing docker inspect container

**Comment by lvenier** [comment]
Docker inspect is not working as expected : Docker do not sort array natively. a simple json comprison is not working :(
