### ISSUE TITLE
:loud_sound: The agent should notify Netbox's journal that the action is pending

### ISSUE THREAD

**Issue by linkdd** [SaaShup/netbox-docker-agent#57]
| Netbox Version | Plugin Version | Agent Version |
| --- | --- | --- |
| 3.6.9 | 1.3.0 | 0.12.1 |

## Actual Behavior

The journal of a container only contain the result of an action ("Start", "Stop", "Recreate", ...).

## Desired Behavior

Whenever I click on an action, there should be an entry in the journal, with the level `info`, to indicate that the action has been received and is currently being processed.

**Comment by lvenier** [comment]
The request makes sense.

A journal entrey will be added on action received by the agent as "Starting", "Stopping", "Recreating", ...

**Comment by lvenier** [comment]
added in https://github.com/SaaShup/netbox-docker-agent/releases/tag/0.13.3
